### ISSUE TITLE
missing Slides.Slide.AboutIdris

### ISSUE THREAD

**Issue by liskin** [raichoo/31C3Slides#1]
Forgot to git add, perhaps?

(Took me a while to figure out what all those

```
Main.idr:92:8:When elaborating right hand side of slides:
Can't unify
    Vect (fromInteger 5 + (fromInteger 6 + (fromInteger 11 + (fromInteger 1 + (fromInteger 1 + fromInteger 2))))) Slide
with
    Vect (plus (length intro) 21) Slide
```

mean, especially as I would expect idris to figure out that intro can't be `Vect 5 Slide` with only 4 list items. But I know nothing at all about it, I hope to learn on the train tomorrow. :-))

**Comment by raichoo** [comment]
Should be fixed now :) Thanks for reporting
